/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cars/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Cars */
        get: operations["get_all_cars_api_v1_cars__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cars/{car_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Car By Id */
        get: operations["get_car_by_id_api_v1_cars__car_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cars/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Cars By Filter */
        post: operations["get_cars_by_filter_api_v1_cars_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/colors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Colors */
        get: operations["get_all_colors_api_v1_colors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Brands */
        get: operations["get_all_brands_api_v1_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{brand_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Models By Brand Id */
        get: operations["get_models_by_brand_id_api_v1_brands__brand_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Configurations By Model Id */
        get: operations["get_configurations_by_model_id_api_v1_models__model_id__configurations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engine_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Engine Types */
        get: operations["get_engine_types_api_v1_engine_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transmission_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transmission Types */
        get: operations["get_transmission_types_api_v1_transmission_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Body Types */
        get: operations["get_body_types_api_v1_body_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_get_cars_by_filter_api_v1_cars_search_post */
        Body_get_cars_by_filter_api_v1_cars_search_post: {
            /** Engine Types */
            engine_types?: string[] | null;
            /** Transmission Types */
            transmission_types?: string[] | null;
            /** Body Types */
            body_types?: string[] | null;
            /** Brand Ids */
            brand_ids?: number[] | null;
            /** Model Ids */
            model_ids?: number[] | null;
            /** Configuration Ids */
            configuration_ids?: number[] | null;
            /** Color Ids */
            color_ids?: number[] | null;
            /** Seller Ids */
            seller_ids?: number[] | null;
        };
        /** CarBrandResponse */
        CarBrandResponse: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Mark */
            mark: string;
        };
        /** CarModelResponse */
        CarModelResponse: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Brand Id */
            brand_id: number;
            /** Model */
            model: string;
        };
        /** CarResponse */
        CarResponse: {
            /** Id */
            id: number;
            /** Inner Id */
            inner_id: number;
            /** Url */
            url: string;
            /** Year */
            year: number;
            /** Price */
            price: number;
            /** Price Rub */
            price_rub: number | null;
            /** Km Age */
            km_age: number | null;
            /** Engine Type */
            engine_type: string | null;
            /** Transmission Type */
            transmission_type: string | null;
            /** Body Type */
            body_type: string | null;
            /** Address */
            address: string | null;
            /** Section */
            section: string | null;
            /** Year Month */
            year_month: string | null;
            brand: components["schemas"]["CarBrandResponse"];
            model: components["schemas"]["CarModelResponse"];
            configuration: components["schemas"]["ConfigurationResponse"];
            color: components["schemas"]["ColorResponse"] | null;
            seller: components["schemas"]["SellerResponse"] | null;
            /** Images */
            images: components["schemas"]["ProductImageResponse"][];
        };
        /** ColorResponse */
        ColorResponse: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Color */
            color: string;
        };
        /** ConfigurationResponse */
        ConfigurationResponse: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Model Id */
            model_id: number;
            /** Configuration */
            configuration: string;
            /** Complectation */
            complectation: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProductImageResponse */
        ProductImageResponse: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Product Id */
            product_id: number;
            /** Image Url */
            image_url: string;
        };
        /** SellerResponse */
        SellerResponse: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Seller */
            seller: string;
            /** Seller Type */
            seller_type: string;
            /** Is Dealer */
            is_dealer: boolean;
            /** Salon Id */
            salon_id: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_all_cars_api_v1_cars__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_car_by_id_api_v1_cars__car_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                car_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarResponse"];
                };
            };
            /** @description Car not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cars_by_filter_api_v1_cars_search_post: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                id?: number | null;
                start_year?: number | null;
                end_year?: number | null;
                lowest_price?: number | null;
                highest_price?: number | null;
                lowest_km_age?: number | null;
                highest_km_age?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_get_cars_by_filter_api_v1_cars_search_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_colors_api_v1_colors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorResponse"][];
                };
            };
        };
    };
    get_all_brands_api_v1_brands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarBrandResponse"][];
                };
            };
        };
    };
    get_models_by_brand_id_api_v1_brands__brand_id__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarModelResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_configurations_by_model_id_api_v1_models__model_id__configurations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_engine_types_api_v1_engine_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_transmission_types_api_v1_transmission_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_body_types_api_v1_body_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
