/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/clients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find Clients */
        get: operations["find_clients_api_v1_clients__get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_v1_clients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_api_v1_clients__client_id__delete"];
        options?: never;
        head?: never;
        /** Patch Client */
        patch: operations["patch_client_api_v1_clients__client_id__patch"];
        trace?: never;
    };
    "/api/v1/clients/{client_id}/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visits */
        get: operations["get_visits_api_v1_clients__client_id__visits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find Doctors */
        get: operations["find_doctors_api_v1_doctors__get"];
        put?: never;
        /** Create Doctor */
        post: operations["create_doctor_api_v1_doctors__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/{doctor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctor */
        get: operations["get_doctor_api_v1_doctors__doctor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Doctor */
        patch: operations["patch_doctor_api_v1_doctors__doctor_id__patch"];
        trace?: never;
    };
    "/api/v1/doctors/{doctor_id}/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visits */
        get: operations["get_visits_api_v1_doctors__doctor_id__visits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visits */
        get: operations["get_visits_api_v1_visits__get"];
        put?: never;
        /** Create Visit */
        post: operations["create_visit_api_v1_visits__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visit */
        get: operations["get_visit_api_v1_visits__visit_id__get"];
        put?: never;
        post?: never;
        /** Delete Visit */
        delete: operations["delete_visit_api_v1_visits__visit_id__delete"];
        options?: never;
        head?: never;
        /** Patch Visit */
        patch: operations["patch_visit_api_v1_visits__visit_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClientCreateRequest */
        ClientCreateRequest: {
            /** Full Name */
            full_name: string;
            /** Name */
            name?: string | null;
            /** Surname */
            surname?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** Phone Number */
            phone_number: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth?: string | null;
        };
        /** ClientResponse */
        ClientResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dt Created
             * Format: date-time
             */
            dt_created: string;
            /**
             * Dt Updated
             * Format: date-time
             */
            dt_updated: string;
            /** Name */
            name: string;
            /** Surname */
            surname: string;
            /** Patronymic */
            patronymic: string | null;
            /** Full Name */
            full_name: string;
            /** Phone Number */
            phone_number: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth?: string | null;
        };
        /** ClientUpdateRequest */
        ClientUpdateRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Name */
            name?: string | null;
            /** Surname */
            surname?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
        };
        /** DoctorCreateRequest */
        DoctorCreateRequest: {
            /** Full Name */
            full_name: string;
            /** Name */
            name?: string | null;
            /** Surname */
            surname?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** Speciality */
            speciality: string;
        };
        /** DoctorResponse */
        DoctorResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dt Created
             * Format: date-time
             */
            dt_created: string;
            /**
             * Dt Updated
             * Format: date-time
             */
            dt_updated: string;
            /** Name */
            name: string;
            /** Surname */
            surname: string;
            /** Patronymic */
            patronymic: string | null;
            /** Full Name */
            full_name: string;
            /** Speciality */
            speciality: string;
        };
        /** DoctorUpdateRequest */
        DoctorUpdateRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Name */
            name?: string | null;
            /** Surname */
            surname?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** Speciality */
            speciality?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PageResponse[VisitResponse] */
        PageResponse_VisitResponse_: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["VisitResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VisitCreateRequest */
        VisitCreateRequest: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Doctor Id
             * Format: uuid
             */
            doctor_id: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Cabinet */
            cabinet?: string | null;
            /**
             * Procedure
             * @default
             */
            procedure: string | null;
            /**
             * Cost
             * @default 0
             */
            cost: number | null;
        };
        /** VisitResponse */
        VisitResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dt Created
             * Format: date-time
             */
            dt_created: string;
            /**
             * Dt Updated
             * Format: date-time
             */
            dt_updated: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Doctor Id
             * Format: uuid
             */
            doctor_id: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /** Cabinet */
            cabinet?: string | null;
            /** Procedure */
            procedure?: string | null;
            /**
             * Cost
             * @default 0
             */
            cost: number | null;
            status: components["schemas"]["VisitStatusEnum"];
            /** Client Name */
            client_name: string;
            /** Client Phone Number */
            client_phone_number: string;
            /** Doctor Name */
            doctor_name: string;
        };
        /**
         * VisitStatusEnum
         * @enum {string}
         */
        VisitStatusEnum: "UNCONFIRMED" | "CONFIRMED" | "PAID";
        /** VisitUpdateRequest */
        VisitUpdateRequest: {
            /** Client Id */
            client_id?: string | null;
            /** Doctor Id */
            doctor_id?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Cost */
            cost?: number | null;
            /** Cabinet */
            cabinet?: string | null;
            /** Procedure */
            procedure?: string | null;
            status?: components["schemas"]["VisitStatusEnum"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    find_clients_api_v1_clients__get: {
        parameters: {
            query?: {
                search_substr?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_clients__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Client with this phone number already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error, invalid data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_client_api_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Client with this uuid not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_client_api_v1_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_v1_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visits_api_v1_clients__client_id__visits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_doctors_api_v1_doctors__get: {
        parameters: {
            query?: {
                search_substr?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_doctor_api_v1_doctors__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_doctor_api_v1_doctors__doctor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Doctor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_doctor_api_v1_doctors__doctor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Doctor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visits_api_v1_doctors__doctor_id__visits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visits_api_v1_visits__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                client_id?: string | null;
                doctor_id?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                cabinet?: string | null;
                procedure?: string | null;
                status?: components["schemas"]["VisitStatusEnum"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_VisitResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_visit_api_v1_visits__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_visit_api_v1_visits__visit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_visit_api_v1_visits__visit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_visit_api_v1_visits__visit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
