"""add phone number unique index

Revision ID: e443d02f9065
Revises: 072ab0e3fab9
Create Date: 2025-08-02 11:40:37.461085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e443d02f9065'
down_revision: Union[str, None] = '072ab0e3fab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__client__id'), 'client', ['id'])
    op.create_unique_constraint(op.f('uq__client__phone_number'), 'client', ['phone_number'])
    op.create_unique_constraint(op.f('uq__doctor__id'), 'doctor', ['id'])
    op.create_unique_constraint(op.f('uq__visit__id'), 'visit', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__visit__id'), 'visit', type_='unique')
    op.drop_constraint(op.f('uq__doctor__id'), 'doctor', type_='unique')
    op.drop_constraint(op.f('uq__client__phone_number'), 'client', type_='unique')
    op.drop_constraint(op.f('uq__client__id'), 'client', type_='unique')
    # ### end Alembic commands ###
