"""add full_name column into db

Revision ID: 3896c407a6e4
Revises: e443d02f9065
Create Date: 2025-08-02 12:27:02.134804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'V3'
down_revision: Union[str, None] = 'V2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('full_name', sa.TEXT(), nullable=True))
    op.add_column('doctor', sa.Column('full_name', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###

    conn = op.get_bind()

    conn.execute(sa.text("""
        UPDATE client
        SET full_name = surname || ' ' || name || ' ' || COALESCE(patronymic, '')
        WHERE full_name IS NULL
    """))
    conn.execute(sa.text("""
        UPDATE doctor
        SET full_name = surname || ' ' || name || ' ' || COALESCE(patronymic, '')
        WHERE full_name IS NULL
    """))

    op.alter_column('client', 'full_name', nullable=False)
    op.alter_column('doctor', 'full_name', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'full_name')
    op.drop_column('client', 'full_name')
    # ### end Alembic commands ###
