"""changed visit date&time structure

Revision ID: V4
Revises: V3
Create Date: 2025-09-08 20:34:31.293720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'V4'
down_revision: Union[str, None] = 'V3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('visit', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + interval '1 hour'"), nullable=False))
    op.drop_column('visit', 'date')
    op.drop_column('visit', 'end_time')
    op.drop_column('visit', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('start_time', postgresql.TIME(), server_default=sa.text('CURRENT_TIME'), autoincrement=False, nullable=False))
    op.add_column('visit', sa.Column('end_time', postgresql.TIME(), server_default=sa.text('CURRENT_TIME'), autoincrement=False, nullable=False))
    op.add_column('visit', sa.Column('date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.drop_column('visit', 'end_date')
    op.drop_column('visit', 'start_date')
    # ### end Alembic commands ###
